using System.Linq;

public static class Problem2
{
    // Even Fibonacci Numbers

    // Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    // By starting with 1 and 2, the first 10 terms will be:
    // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    // By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    // find the sum of the even-valued terms.

    public static long SumEvenFib(int upTo)
    {
        int sumEvenFib = 0, num = 1, prevNum = 1;
        
        for (int i = 1; num <= upTo; i++)
        {
            num += prevNum;
            prevNum = num - prevNum;
            int even = Convert.ToInt32((num & 1) == 0);
            sumEvenFib += even * num;
        }

        return sumEvenFib;
    }
}